spring:
    datasource: 
        url: jdbc:mariadb://localhost:3306/database_db
        username: root
        password: claroemmans
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update  
        show-sql: true  